apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-pages
  labels:
    app: error-pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: error-pages
  template:
    metadata:
      labels:
        app: error-pages
    spec:
      containers:
      - name: error-pages
        image: tarampampam/error-pages
        env:
        - name: TEMPLATE_NAME
          value: "hacker-terminal"
        - name: SHOW_DETAILS
          value: "true"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: error-pages
  labels:
    app: error-pages
spec:
  selector:
    app: error-pages
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
