apiVersion: apps/v1
kind: Deployment
metadata:
  name: orquestador-deployment
  labels:
    app: orquestador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orquestador
  template:
    metadata:
      labels:
        app: orquestador
    spec:
      containers:
        - name: orquestador
          image: santiagosanchez03/orquestador-service:latest  # Reemplaza con la imagen adecuada
          ports:
            - containerPort: 4005
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4005"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:4000"
            - name: JOURNAL_SERVICE_URL
              value: "http://journal-service:4002"
            - name: USER_SERVICE_URL
              value: "http://user-service:4001"
---
apiVersion: v1
kind: Service
metadata:
  name: orquestador-service
  labels:
    app: orquestador
spec:
  type: ClusterIP # Cambia a NodePort o LoadBalancer si necesitas acceso externo
  ports:
    - port: 4005
      targetPort: 4005
      protocol: TCP
  selector:
    app: orquestador
