apiVersion: apps/v1
kind: Deployment
metadata:
  name: orquestador-deployment
  labels:
    app: orquestador
spec:
  replicas: 3  # Número de réplicas del pod
  selector:
    matchLabels:
      app: orquestador
  template:
    metadata:
      labels:
        app: orquestador
    spec:
      containers:
        - name: orquestador
          image: santiagosanchez03/orquestador-service:latest  # Reemplaza con la imagen adecuada
          ports:
            - containerPort: 4005
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4005"
          readinessProbe: # Para verificar que el servicio esté listo
            httpGet:
              path: /
              port: 4005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe: # Para verificar que el contenedor sigue vivo
            httpGet:
              path: /
              port: 4005
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: orquestador-service
  labels:
    app: orquestador
spec:
  type: ClusterIP # Cambia a NodePort o LoadBalancer si necesitas acceso externo
  ports:
    - port: 4005
      targetPort: 4005
      protocol: TCP
  selector:
    app: orquestador
