apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: eydersantiago/auth-service  # Aquí pones tu imagen de Docker si está en un registro público o privado
          ports:
            - containerPort: 4000 
          env:
            - name: PORT
              value: "4000" 

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000 
      nodePort: 30673
  type: NodePort
