apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: eydersantiago/user-service  # Aquí pones tu imagen de Docker si está en un registro público o privado
          ports:
            - containerPort: 4001 
          env:
            - name: PORT
              value: "4001" 

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001 
  type: NodePort 
