apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: eydersantiago/user-service2
          ports:
            - containerPort: 4001 
          env:
            - name: PORT
              value: "4001" 

---
apiVersion: v1
kind: Service
metadata:
  name: user-service2
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001
  type: ClusterIP
