version: '3.8'

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      PORT: 4000

  journal:
    build:
      context: ./journal
      dockerfile: Dockerfile
    ports:
      - "4002:4002" 
    environment:
      NODE_ENV: production
      PORT: 4002

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "4001:4001" 
    environment:
      NODE_ENV: production
      PORT: 4001

  orquestador:
    build:
      context: ./orquestador
      dockerfile: Dockerfile
    ports:
      - "4005:4005"
    environment:
      NODE_ENV: production
      PORT: 4005
    depends_on:
      - auth
      - journal
      - user