version: '3.7'

services:
  auth:
    build: ./auth
    ports:
      - "4000:4000"
    # Aquí tu microservicio ya debería exponer /metrics en 4000

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - auth

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3009:3000"
    depends_on:
      - prometheus