apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal
  labels:
    app: journal
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: journal
  template:
    metadata:
      labels:
        app: journal
    spec:
      containers:
        - name: journal
          image: eydersantiago/journal-service  # Aquí pones tu imagen de Docker si está en un registro público o privado
          ports:
            - containerPort: 4002 
          env:
            - name: PORT
              value: "4002" 

---
apiVersion: v1
kind: Service
metadata:
  name: journal-service
spec:
  selector:
    app: journal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4002 
  type: NodePort
